name: Deploy to Ubuntu Server
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Deploy Code
        uses: appleboy/ssh-action@master
        with:
          host: 170.64.165.197
          username: root
          key: ${{ secrets.DEPLOY_KEY }}
          port: 22
          script: |
            cd /var/www/html
            git pull
            # Additional deployment commands go here.
